
#ifndef FAULTMANAGER_CNF_GEN_H
#define FAULTMANAGER_CNF_GEN_H
/* 
 * This file is auto-generated by the faultmanager_cnf_generator tool.
 * Do not edit this file directly. Instead, edit the source configuration
 * and regenerate this file.
*/
#include "faultmanager_types.h"

#define NUM_FAULTS 5

#define SensorFailure_Fault_Id 0
#define CommunicationError_Fault_Id 1
#define PowerFailure_Fault_Id 2
#define Overheating_Fault_Id 3
#define SoftwareError_Fault_Id 4

extern Fault fault_cnf[NUM_FAULTS];
#endif // FAULTMANAGER_CNF_GEN_H