
/* 
 * This file is auto-generated by the faultmanager_cnf_generator tool.
 * Do not edit this file directly. Instead, edit the source configuration
 * and regenerate this file.
*/

#include "faultmanager_cnf_gen.h"
#include "callback.h"

Fault fault_cnf[NUM_FAULTS] = {
    { SensorFailure_Fault_Id, SensorFailure, Medium, 3, 2, NULL, LogFault | NotifyUser },
    { CommunicationError_Fault_Id, CommunicationError, High, 4, 3, communication_error_handler, LogFault | NotifyUser },
    { PowerFailure_Fault_Id, PowerFailure, High, 5, 4, NULL, LogFault | NotifyUser | ShutdownSystem },
    { Overheating_Fault_Id, Overheating, High, 4, 3, NULL, LogFault | NotifyUser | ShutdownSystem },
    { SoftwareError_Fault_Id, SoftwareError, Medium, 3, 2, NULL, LogFault | NotifyUser }
};  