#ifndef FAULTMANAGER_CNF_GEN_H
#define FAULTMANAGER_CNF_GEN_H

/* 
 * This file is auto-generated by the faultmanager_cnf_generator tool.
 * Do not edit this file directly. Instead, edit the source configuration
 * and regenerate this file.
*/
#include "faultmanager_types.h"

#define NUM_FAULTS {{faults|length}}

{%-for fault in faults %}
#define {{fault.id}} {{loop.index0}}
{%-endfor%}

extern Fault fault_cnf[NUM_FAULTS];
#endif // FAULTMANAGER_CNF_GEN_H