
/* 
 * This file is auto-generated by the faultmanager_cnf_generator tool.
 * Do not edit this file directly. Instead, edit the source configuration
 * and regenerate this file.
*/

#include "faultmanager_cnf_gen.h"
#include "callback.h"

Fault fault_definitions[NUM_FAULTS] = {
    {%for fault in faults-%}
     { {{fault.id}}, {{fault.type}}, {{fault.severity}}, {{fault.confirmed_threshold}}, {{fault.heal_threshold}}, {{fault.on_confirmed}}, {{fault.FaultAction}} } 
     {%- if not loop.last -%},{%- endif %}
    {%endfor%}
};  